import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../scss/main.scss'
import { ProviderAtividade } from '@/context/context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sistema Compuservice',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({children}: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ProviderAtividade>
            {children}
          </ProviderAtividade>
        </body>
    </html>
  )
}
